# Generated by Django 5.0.2 on 2025-11-22 16:11

import pgvector.django
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property_type', models.CharField(choices=[('PLOT', 'Plot'), ('APARTMENT', 'Apartment'), ('COMMERCIAL', 'Commercial')], max_length=20)),
                ('listing_type', models.CharField(choices=[('SELL', 'Sell'), ('RENT', 'Rent'), ('NEW_LAUNCH', 'New Launch')], max_length=20)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('address_line', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('is_thumbnail', models.BooleanField(default=False)),
            ],
        ),
    ]
