# Generated by Django 5.0.2 on 2025-11-23 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
        migrations.AddField(
            model_name='property',
            name='doc_7_12',
            field=models.FileField(blank=True, null=True, upload_to='docs/7_12/'),
        ),
        migrations.AddField(
            model_name='property',
            name='doc_building_perm',
            field=models.FileField(blank=True, null=True, upload_to='docs/building_perm/'),
        ),
        migrations.AddField(
            model_name='property',
            name='doc_floor_plan',
            field=models.FileField(blank=True, null=True, upload_to='docs/floor_plan/'),
        ),
        migrations.AddField(
            model_name='property',
            name='doc_layout_copy',
            field=models.FileField(blank=True, null=True, upload_to='docs/layout_copy/'),
        ),
        migrations.AddField(
            model_name='property',
            name='doc_layout_order',
            field=models.FileField(blank=True, null=True, upload_to='docs/layout_order/'),
        ),
        migrations.AddField(
            model_name='property',
            name='doc_mojani',
            field=models.FileField(blank=True, null=True, upload_to='docs/mojani/'),
        ),
        migrations.AddField(
            model_name='property',
            name='doc_na_order',
            field=models.FileField(blank=True, null=True, upload_to='docs/na_order/'),
        ),
        migrations.AddField(
            model_name='property',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='property',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified & Live'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('FLAT', 'Flat/Apartment'), ('LAND', 'Residential Land'), ('SERVICED_APT', 'Serviced Apartments'), ('BUILDER_FLOOR', 'Independent/Builder Floor'), ('STUDIO', '1 RK/Studio Apartment'), ('VILLA', 'Independent House/Villa'), ('FARMHOUSE', 'Farm House'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'property')},
            },
        ),
    ]
