# Generated by Django 5.0.2 on 2025-11-22 16:11

import apps.mandates.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deal_type', models.CharField(choices=[('WITH_BROKER', 'With Broker'), ('WITH_PLATFORM', 'With Platform')], max_length=20)),
                ('initiated_by', models.CharField(choices=[('SELLER', 'Seller'), ('BROKER', 'Broker')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.mandates.models.get_expiry)),
            ],
        ),
    ]
